spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      mysql:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://192.168.3.211/zfh_iot?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
        username: root
        password: iamadoctor
        initial-size: 10
        min-idle: 10
        max-active: 100
        max-wait: 60000
        
  redis:
    host: 192.168.3.211
    port: 6379
    password: iamadoctor
    database: 3
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
